pet 28 jun 2024 10:25:10 CEST
Traceback (most recent call last):
  File "/home/dis/miniconda3/bin/conda", line 12, in <module>
    from conda.cli import main
  File "/home/dis/miniconda3/lib/python3.12/site-packages/conda/__init__.py", line 6, in <module>
    from json import JSONEncoder
  File "/home/dis/miniconda3/lib/python3.12/json/__init__.py", line 107, in <module>
    from .encoder import JSONEncoder
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1124, in get_code
  File "<frozen importlib._bootstrap_external>", line 753, in _compile_bytecode
KeyboardInterrupt
pet 28 jun 2024 10:29:16 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
{'rgb': {'resolution_x': 1920, 'resolution_y': 1080, 'fps': 30.0, 'channel': 0}, 'hires': {'resolution_x': 3840, 'resolution_y': 2160, 'fps': 10.0, 'channel': 2}, 'thermal': {'resolution_x': 160, 'resolution_y': 120, 'fps': 8.0, 'to_celsius': 'True'}, 'depth': {'resolution_x': 640, 'resolution_y': 480, 'fps': 30.0}, 'audio': {'sampling_rate': 16000, 'n_channels': 1, 'chunk_length': 7200}}
Brio channel: 4
Brio channel: 2
StreamCam channel: 0
{'rgb': {'resolution_x': 1920, 'resolution_y': 1080, 'fps': 30.0, 'channel': 0}, 'hires': {'resolution_x': 3840, 'resolution_y': 2160, 'fps': 10.0, 'channel': 2}, 'thermal': {'resolution_x': 160, 'resolution_y': 120, 'fps': 8.0, 'to_celsius': 'True'}, 'depth': {'resolution_x': 640, 'resolution_y': 480, 'fps': 30.0}, 'audio': {'sampling_rate': 16000, 'n_channels': 1, 'chunk_length': 7200}}
{'rgb': {'resolution_x': 1920, 'resolution_y': 1080, 'fps': 30.0, 'channel': 0}, 'hires': {'resolution_x': 3840, 'resolution_y': 2160, 'fps': 10.0, 'channel': 2}, 'thermal': {'resolution_x': 160, 'resolution_y': 120, 'fps': 8.0, 'to_celsius': 'True'}, 'depth': {'resolution_x': 640, 'resolution_y': 480, 'fps': 30.0}, 'audio': {'sampling_rate': 16000, 'n_channels': 1, 'chunk_length': 7200}}
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.018] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video13): can't open camera by index
[ WARN:0@61.018] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 200, in <module>
    capture.capture()
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 176, in capture
    process.join()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Process Process-4:
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/realsense.py", line 84, in captureImages
    frames = self.pipeline.wait_for_frames(10000)
RuntimeError: Frame didn't arrive within 10000

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dis/trust-me-setup/installers/data_capture/realsense.py", line 84, in captureImages
    frames = self.pipeline.wait_for_frames(10000)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
pet 28 jun 2024 10:33:21 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
{'rgb': {'resolution_x': 1920, 'resolution_y': 1080, 'fps': 30.0, 'channel': 0}, 'hires': {'resolution_x': 3840, 'resolution_y': 2160, 'fps': 10.0, 'channel': 2}, 'thermal': {'resolution_x': 160, 'resolution_y': 120, 'fps': 8.0, 'to_celsius': 'True'}, 'depth': {'resolution_x': 640, 'resolution_y': 480, 'fps': 30.0}, 'audio': {'sampling_rate': 16000, 'n_channels': 1, 'chunk_length': 7200}}
Brio channel: 4
Brio channel: 2
StreamCam channel: 0
{'rgb': {'resolution_x': 1920, 'resolution_y': 1080, 'fps': 30.0, 'channel': 0}, 'hires': {'resolution_x': 3840, 'resolution_y': 2160, 'fps': 10.0, 'channel': 2}, 'thermal': {'resolution_x': 160, 'resolution_y': 120, 'fps': 8.0, 'to_celsius': 'True'}, 'depth': {'resolution_x': 640, 'resolution_y': 480, 'fps': 30.0}, 'audio': {'sampling_rate': 16000, 'n_channels': 1, 'chunk_length': 7200}}
{'rgb': {'resolution_x': 1920, 'resolution_y': 1080, 'fps': 30.0, 'channel': 0}, 'hires': {'resolution_x': 3840, 'resolution_y': 2160, 'fps': 10.0, 'channel': 2}, 'thermal': {'resolution_x': 160, 'resolution_y': 120, 'fps': 8.0, 'to_celsius': 'True'}, 'depth': {'resolution_x': 640, 'resolution_y': 480, 'fps': 30.0}, 'audio': {'sampling_rate': 16000, 'n_channels': 1, 'chunk_length': 7200}}
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.018] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video13): can't open camera by index
[ WARN:0@61.018] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
[ WARN:0@71.337] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video12): select() timeout.
Process Process-4:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dis/trust-me-setup/installers/data_capture/realsense.py", line 84, in captureImages
    frames = self.pipeline.wait_for_frames(10000)
RuntimeError: Frame didn't arrive within 10000
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 200, in <module>
    capture.capture()
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 176, in capture
    process.join()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
pet 28 jun 2024 14:11:30 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Brio channel: 4
Brio channel: 2
StreamCam channel: 0
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.030] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video13): can't open camera by index
[ WARN:0@61.030] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 200, in <module>
    capture.capture()
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 176, in capture
    process.join()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
ƒçet 04 jul 2024 07:11:23 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
Brio channel: 4
Brio channel: 2
StreamCam channel: 0
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
Traceback (most recent call last):
  File "run_tobii.py", line 24, in <module>
    tracker.start_recording()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/site-packages/pygaze/_eyetracker/libtobii.py", line 198, in start_recording
    if not self.t0 and self._write_enabled:
AttributeError: 'TobiiProTracker' object has no attribute 't0'
/home/dis/trust-me-setup/startup_script.sh: line 52: pygame: command not found
[ WARN:0@61.014] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video13): can't open camera by index
[ WARN:0@61.014] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
[ WARN:0@71.310] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video12): select() timeout.
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/streamdeck/run_streamdeck.py", line 281, in <module>
    while deck.is_open():
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/site-packages/StreamDeck/Devices/StreamDeck.py", line 234, in is_open
    return self.device.is_open()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/site-packages/StreamDeck/Transport/LibUSBHIDAPI.py", line 381, in is_open
    with self.mutex:
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 200, in <module>
    capture.capture()
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 176, in capture
    process.join()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
pet 05 jul 2024 08:42:40 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
Brio channel: 4
Brio channel: 2
StreamCam channel: 0
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
Traceback (most recent call last):
  File "run_tobii.py", line 24, in <module>
    tracker.start_recording()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/site-packages/pygaze/_eyetracker/libtobii.py", line 198, in start_recording
    if not self.t0 and self._write_enabled:
AttributeError: 'TobiiProTracker' object has no attribute 't0'
/home/dis/trust-me-setup/startup_script.sh: line 52: pygame: command not found
[ WARN:0@60.994] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video13): can't open camera by index
[ WARN:0@60.994] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
pet 05 jul 2024 09:33:26 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
Brio channel: 4
Brio channel: 2
StreamCam channel: 0
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
Traceback (most recent call last):
  File "run_tobii.py", line 24, in <module>
    tracker.start_recording()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/site-packages/pygaze/_eyetracker/libtobii.py", line 198, in start_recording
    if not self.t0 and self._write_enabled:
AttributeError: 'TobiiProTracker' object has no attribute 't0'
/home/dis/trust-me-setup/startup_script.sh: line 52: pygame: command not found
[ WARN:0@61.030] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video13): can't open camera by index
[ WARN:0@61.030] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
[ WARN:0@71.493] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video12): select() timeout.
Process Process-4:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dis/trust-me-setup/installers/data_capture/realsense.py", line 85, in captureImages
    frames = self.pipeline.wait_for_frames(10000)
RuntimeError: Frame didn't arrive within 10000
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/streamdeck/run_streamdeck.py", line 282, in <module>
    deck.set_key_callback(key_change_callback)
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 200, in <module>
    capture.capture()
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 176, in capture
    process.join()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
                                                                                                                                                                                                                                                                                                                                                                  pon 08 jul 2024 10:34:35 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
StreamCam channel: 0
Brio channel: 2
Brio channel: 0
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@0.950] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[ERROR:0@1.069] global obsensor_uvc_stream_channel.cpp:158 getStreamChannelGroup Camera index out of range
None
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.027] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video13): can't open camera by index
[ WARN:0@61.027] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
pon 08 jul 2024 10:38:55 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
StreamCam channel: 2
Brio channel: 2
Brio channel: 0
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.013] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video11): can't open camera by index
[ WARN:0@61.013] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
[ WARN:0@71.919] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
Process Process-4:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dis/trust-me-setup/installers/data_capture/realsense.py", line 85, in captureImages
    frames = self.pipeline.wait_for_frames(10000)
RuntimeError: Frame didn't arrive within 10000
pon 08 jul 2024 10:43:09 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
StreamCam channel: 2
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@0.608] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[ERROR:0@0.608] global obsensor_uvc_stream_channel.cpp:158 getStreamChannelGroup Camera index out of range
None
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
Traceback (most recent call last):
  File "run_tobii.py", line 24, in <module>
    tracker.start_recording()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/site-packages/pygaze/_eyetracker/libtobii.py", line 198, in start_recording
    if not self.t0 and self._write_enabled:
AttributeError: 'TobiiProTracker' object has no attribute 't0'
/home/dis/trust-me-setup/startup_script.sh: line 52: pygame: command not found
[ WARN:0@60.696] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video1): can't open camera by index
[ WARN:0@60.696] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
[ WARN:0@60.696] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[ WARN:0@60.696] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
Process Process-4:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dis/trust-me-setup/installers/data_capture/realsense.py", line 67, in captureImages
    self.profile = self.pipeline.start(self.config)
RuntimeError: No device connected
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 200, in <module>
    capture.capture()
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 176, in capture
    process.join()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
pon 08 jul 2024 11:04:30 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
StreamCam channel: 6
Brio channel: 4
Brio channel: 2
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.522] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video1): can't open camera by index
[ WARN:0@61.522] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 200, in <module>
    capture.capture()
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 176, in capture
    process.join()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
pon 08 jul 2024 11:07:27 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
StreamCam channel: 6
Brio channel: 4
Brio channel: 2
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.487] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video1): can't open camera by index
[ WARN:0@61.487] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
[ WARN:0@71.681] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video0): select() timeout.
Process Process-4:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dis/trust-me-setup/installers/data_capture/realsense.py", line 85, in captureImages
    frames = self.pipeline.wait_for_frames(10000)
RuntimeError: Frame didn't arrive within 10000
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 200, in <module>
    capture.capture()
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 176, in capture
    process.join()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
/home/dis/trust-me-setup/installers/data_capture/microphone.py:80: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  recording_np = np.concatenate(np.array(self.recording), axis=0)
Exception ignored from cffi callback <function _StreamBase.__init__.<locals>.callback_ptr at 0x7ff4325b6d30>:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/site-packages/sounddevice.py", line 846, in callback_ptr
    return _wrap_callback(callback, data, frames, time, status)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/site-packages/sounddevice.py", line 2687, in _wrap_callback
    callback(*args)
  File "/home/dis/trust-me-setup/installers/data_capture/microphone.py", line 33, in callback
    print(f"Error: {status}", flush=True)
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
tor 09 jul 2024 09:54:00 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
StreamCam channel: 6
Brio channel: 4
Brio channel: 2
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.482] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video1): can't open camera by index
[ WARN:0@61.482] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      tor 09 jul 2024 10:06:31 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
StreamCam channel: 6
Brio channel: 4
Brio channel: 2
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.504] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video1): can't open camera by index
[ WARN:0@61.504] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/streamdeck/run_streamdeck.py", line 281, in <module>
    while deck.is_open():
KeyboardInterrupt
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 200, in <module>
    capture.capture()
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 176, in capture
    process.join()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
ƒçet 11 jul 2024 07:08:41 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
StreamCam channel: 0
Brio channel: 8
Brio channel: 6
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@1.005] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[ERROR:0@1.129] global obsensor_uvc_stream_channel.cpp:158 getStreamChannelGroup Camera index out of range
None
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.080] global cap_v4l.cpp:889 requestBuffers VIDEOIO(V4L2:/dev/video6): failed VIDIOC_REQBUFS: errno=19 (No such device)
[ WARN:0@61.082] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video13): can't open camera by index
[ WARN:0@61.082] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 200, in <module>
    capture.capture()
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 176, in capture
    process.join()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
ƒçet 11 jul 2024 07:12:04 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
StreamCam channel: 0
Brio channel: 2
Brio channel: 0
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@0.941] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[ERROR:0@1.060] global obsensor_uvc_stream_channel.cpp:158 getStreamChannelGroup Camera index out of range
None
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
Process Process-4:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dis/trust-me-setup/installers/data_capture/realsense.py", line 60, in captureImages
    start_event.wait()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/synchronize.py", line 349, in wait
    self._cond.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/synchronize.py", line 261, in wait
    return self._wait_semaphore.acquire(True, timeout)
KeyboardInterrupt
Process Process-1:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dis/trust-me-setup/installers/data_capture/camera.py", line 75, in captureImages
    start_event.wait()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/synchronize.py", line 349, in wait
    self._cond.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/synchronize.py", line 261, in wait
    return self._wait_semaphore.acquire(True, timeout)
KeyboardInterrupt
Process Process-5:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dis/trust-me-setup/installers/data_capture/thermal.py", line 59, in captureImages
    start_event.wait()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/synchronize.py", line 349, in wait
    self._cond.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/synchronize.py", line 261, in wait
    return self._wait_semaphore.acquire(True, timeout)
KeyboardInterrupt
Process Process-3:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dis/trust-me-setup/installers/data_capture/microphone.py", line 49, in record
    event.wait()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/synchronize.py", line 349, in wait
    self._cond.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/synchronize.py", line 261, in wait
    return self._wait_semaphore.acquire(True, timeout)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
ƒçet 11 jul 2024 07:30:11 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/auto_config_hw.py", line 34, in <module>
    channel = int(dev[-2:])
ValueError: invalid literal for int() with base 10: 'o0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/auto_config_hw.py", line 37, in <module>
    print(e)
NameError: name 'e' is not defined
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@0.948] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video10): can't open camera by index
[ERROR:0@1.067] global obsensor_uvc_stream_channel.cpp:158 getStreamChannelGroup Camera index out of range
None
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 200, in <module>
    capture.capture()
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 176, in capture
    process.join()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
ƒçet 11 jul 2024 07:35:10 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
StreamCam channel: 0
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@0.990] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video0): can't open camera by index
[ERROR:0@1.078] global obsensor_uvc_stream_channel.cpp:158 getStreamChannelGroup Camera index out of range
None
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@71.343] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video8): select() timeout.
[ WARN:0@71.349] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video9): can't open camera by index
[ WARN:0@71.349] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 200, in <module>
    capture.capture()
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 176, in capture
    process.join()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
ƒçet 11 jul 2024 07:43:41 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
Brio channel: 12
Brio channel: 10
StreamCam channel: 8
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.517] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video7): can't open camera by index
[ WARN:0@61.517] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 200, in <module>
    capture.capture()
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 176, in capture
    process.join()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
ƒçet 11 jul 2024 07:48:30 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
Brio channel: 12
Brio channel: 10
StreamCam channel: 8
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
[ WARN:0@61.524] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video7): can't open camera by index
[ WARN:0@61.524] global cap.cpp:342 open VIDEOIO(V4L2): backend is generally available but can't be used to capture by index
[ WARN:0@72.368] global cap_v4l.cpp:1136 tryIoctl VIDEOIO(V4L2:/dev/video6): select() timeout.
Traceback (most recent call last):
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 200, in <module>
    capture.capture()
  File "/home/dis/trust-me-setup/installers/data_capture/capture_data.py", line 176, in capture
    process.join()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 149, in join
    res = self._popen.wait(timeout)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 47, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
pon 15 jul 2024 11:18:50 CEST
conda 24.4.0
Video now available. Starting script...
Started recording tobii
Streamdeck running
Brio channel: 2
Brio channel: 0
Started recording RGB
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1089:(snd_pcm_dmix_open) unable to open slave
Process Process-4:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dis/trust-me-setup/installers/data_capture/realsense.py", line 67, in captureImages
    self.profile = self.pipeline.start(self.config)
RuntimeError: xioctl(VIDIOC_S_FMT) failed, errno=16 Last Error: Device or resource busy
Expression 'paInvalidSampleRate' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2043
Expression 'PaAlsaStreamComponent_InitialConfigure( &self->capture, inParams, self->primeBuffers, hwParamsCapture, &realSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2714
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, sampleRate, framesPerBuffer, &inputLatency, &outputLatency, &hostBufferSizeMode )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2838
Process Process-3:
Traceback (most recent call last):
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dis/trust-me-setup/installers/data_capture/microphone.py", line 60, in record
    with sd.InputStream(
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/site-packages/sounddevice.py", line 1421, in __init__
    _StreamBase.__init__(self, kind='input', wrap_callback='array',
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/site-packages/sounddevice.py", line 898, in __init__
    _check(_lib.Pa_OpenStream(self._ptr, iparameters, oparameters,
  File "/home/dis/miniconda3/envs/tobii/lib/python3.8/site-packages/sounddevice.py", line 2747, in _check
    raise PortAudioError(errormsg, err)
sounddevice.PortAudioError: Error opening InputStream: Invalid sample rate [PaErrorCode -9997]
